schema_version = "1.0.0"

id = "frankmocap_blender_addon"
version = "1.0.3"
name = "Frankmocap for Blender"
tagline = "frankmocap body motion capture integration with blender"
maintainer = "Sebastian Tran"
type = "add-on"

website = "https://smpl-x.is.tue.mpg.de/"

tags = ["Animation", "Import-Export", "Rigging"]

blender_version_min = "4.5.0"

license = [
  "SPDX:GPL-2.0-or-later",
]

copyright = [
  "2026 Max Planck Institute for Intelligent Systems",
]

[permissions]
files = "Import pose/animation data, export FBX/Alembic data"
